# Generated by Django 5.0.6 on 2024-06-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('course_id', models.IntegerField()),
                ('country', models.CharField(max_length=28)),
                ('education_level', models.CharField(max_length=35)),
                ('id_number', models.IntegerField()),
                ('subject_specialisation', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=25)),
            ],
        ),
    ]
